name: Schedule

on:
  schedule:
    - cron: '10 * * * *'

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Setup
        run: npm add -g @antfu/ni

      - name: Install
        run: nci

      - name: Run
        run: 'node tools/test.js'
